### PR TITLE
CASMTRIAGE-2793 Deterministic Handling of Multi-Chassis LAGG Deployments

### PR DESCRIPTION
**Pull request by rustydb**
#### Summary and Scope

- Fixes CASMTRIAGE-2793
- Relates to CASMINST-2120

##### Issue Type

- Bugfix Pull Request

This Pull-Request implements enhancements for deployments running over an LACP enabled Multi-Chassis or Standard Link-Aggregation.

##### 1. iPXE no longer tries interfaces one-by-one; open all NICs at once to circumvent Multi-Chassis LAGG Suspension.

**_Problem:_**

Currently, iPXE will iterate on each NIC until one of them provides connectivity. This means iPXE opens one NIC, attempts configuring, and if it fails then it'll close it and move onto the next available NIC.

This behavior works conventionally, in non-BONDed setups. Deploying/booting over a LAGG with this behavior requires adjustments to the switch configurations belonging to the nodes in question. Specifically LAGGed systems require enabling an `lacp-fallback/individual` feature to support non-LACP traffic over a single member of the LAGG while closing the other members.

Relying on `lacp-fallback` has caused us more problems when paired with the iPXE behavior, since iPXE will commonly be 1 or 2 interfaces _ahead_ of what's actually open on the switch. The timeouts on the switch usually prevent it from aligning to the NIC that iPXE is trying.

**_Solution:_**

By opening (without configuring) all NICs we establish L2 connectivity with the switch, and circumvent tripping any `lacp-fallback/individual` suspension/blockers. The MLAG will go into a partial-BOND, the switch will be anticipating either an LACP packet _or_ an individual interface to start transmitting. This anticipation is new, because in this moment we can guarantee a successful attempt for any interface that's `OPEN`.

Code: https://github.com/Cray-HPE/metal-ipxe/blob/2aca3d81d551b50133eda1a7c1207a04101c8cd7/src/config/metal/metal.ipxe#L10-L22

Below is a snippet from iPXE with the new behavior, as one may see we have two CLOSED NICs (onboards) and 2 OPEN NICs. These two OPEN NICs can attempt to DHCP without a fuss.

```bash
=== LINK ===========================================
net0: a4:bf:01:48:1f:6c using x722-10gt on 0000:3d:00.0 (Ethernet) [open]
  [Link:down, TX:0 TXE:0 RX:0 RXE:0]
  [Link status: Down (http://ipxe.org/38086193)]
net1: a4:bf:01:48:1f:6d using x722-10gt on 0000:3d:00.1 (Ethernet) [open]
  [Link:down, TX:0 TXE:0 RX:0 RXE:0]
  [Link status: Down (http://ipxe.org/38086193)]
net2: b8:59:9f:f9:1c:ba using ConnectX-4 on 0001:af:00.0 (Ethernet) [open]
  [Link:up, TX:0 TXE:1 RX:0 RXE:0]
  [TXE: 1 x "Network unreachable (http://ipxe.org/28086090)"]
net3: b8:59:9f:f9:1c:bb using ConnectX-4 on 0001:af:00.1 (Ethernet) [open]
  [Link:up, TX:0 TXE:0 RX:0 RXE:0]
```

> An administrator or triage expert would be able to read that and see whether or not cables were connected and switchports are enabled.

##### 2. DHCP and LACP Adjustments

- `src/config/metal/general.h` The DHCP timeout tweaks were removed in favor of static override of 8 seconds (set in `src/config/metal/metal.ipxe#20`).
- `src/config/metal/general.h` The `LINK_WAIT_TIMEOUT` was reduced to `5 * TICKS_PER_SEC` from `45 * TICKS_PER_SEC`, the higher wait was not helping the MLAG timeout as it was previously thought to have been. The new lower timeout will expedite passing-by actual, un-plugged/disabled interfaces (e.g. onboards).
- `src/usr/ifmgmt.c` verbosity was added to iPXE's `ifconf`'s call to `iflinkwait`, this provides differentiable log messages stating when a LINK and an IP Configuration have taken place. Before this change only the latter (IP Configuration) was logged (see example below):
```bash
=== DHCP ===========================================
Waiting for link-up on net0................. Down (http://ipxe.org/38086193)
Waiting for link-up on net1................. Down (http://ipxe.org/38086193)
Waiting for link-up on net2... ok
Configuring [dhcp] (net2 b8:59:9f:f9:1c:ba)...... ok
```

##### 3. Move DHCP from `mgmt0` to `bond0`

**_Problem:_**

Before, iPXE would tell the kernel that the system should DHCP over `mgmt0`. This was done for simplicity, but it causes problems in a healthy BONDed environment because **it trips the `lacp-fallback/individual`** feature.  If `mgmt0` is not connected to the MASTER in the MLAG then it will be suspended due to favoritism/preference (the switch will favor using master first).

This was causing an undesirable side-effect, despite seeing better iPXE behavior with these changes we were observing cloud-init failing to start, or in some cases dracut would fail to pull the SquashFS.

**_Solution:_**

To prevent from tripping the `lacp-fallback/individual` subroutine unnecessarily, a node needs to start sending LACP packets. The LACP packets will indicate to the switch to start forming an LACP BOND.

This meant adding a _simple_ bond configuration into iPXE to pass into the kernel, as well as moving the request to DHCP from `mgmt0` to `bond0` instead. This means that after iPXE finishes its job and exits, the initrd will form a bond in a healthy switch environment (e.g. an env. that hasn't fallen into suspension/lacp-fallback protocols).

Specifically:
- Before `ip=mgmt0:dhcp` was on the kernel cmdline; now `ip=bond0:dhcp` is used instead
- Before no `bond=` arguments exists on the cmdline (post CASMINST-2120); now `bond0:mgmt0,mgmt1:802.3ad` exists on the cmdline

Dracut will succeed at launching the bond without running into suspended ports, preventing confusion within the Linux network daemons.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (x) (if yes, please include results or a description of the test)
- [x] I have tested this on Dell + Mellanox systems **with LACP-Fallback enabled on all spines** (NOTE: normally LACP-Fallback is enabled on a single-spine as a means to attempt to work around the MLAG-booting issues we've seen).
- [x]  I have tested this on an Aruba equipped system

**waiting to merge until Aruba's PXE and cloud-init cleanly.**

#### Risks and Mitigations
 
What is less risky, or more risky now - or if your mod fails is there a new risk?

### CODE REVIEW

**Review by heemstra — APPROVED** [review]

**Comment by rustydb** [comment]
Pending more testing, there might be a slight image change required for this to succeed as intended. However the image change would be independent, this could merge ahead but at the risk of needing another tweak.

Holding this until EOD while I sort out the image change.

The issue is that despite ipxe and dracut running smoothly cloudinit is failing to setup a default route. This is because the default route initially is going over bond0 now and not mgmt0, and bond* is stripped of IP information prior to the real default route being setup. In other words cloud-init kills itself.

**Comment by rustydb** [comment]
> Pending more testing, there might be a slight image change required for this to succeed as intended. However the image change would be independent, this could merge ahead but at the risk of needing another tweak.
> 
> Holding this until EOD while I sort out the image change.
> 
> The issue is that despite ipxe and dracut running smoothly cloudinit is failing to setup a default route. This is because the default route initially is going over bond0 now and not mgmt0, and bond* is stripped of IP information prior to the real default route being setup. In other words cloud-init kills itself.

The image change that makes that finishes this work is here: https://github.com/Cray-HPE/node-image-build/pull/138

I'm re-validating this metal-ipxe change _with_ that NCN change on Aruba and Mellanox/Dell setups.

**Comment by rustydb** [comment]
Just awaiting final verification on Aruba.
My Aruba system went down today so I'm waiting for another to open up or for the same one to be mended.

**Comment by rustydb** [comment]
The Aruba's are tricky.

**Comment by rustydb** [comment]
I'm debating adding a single retry to the PXE with a sleep of 17 seconds (to go beyond the 15sec STP block). If it fails then notify the user 2 retries failed and the bios will move onto the next boot option.

**Comment by rustydb** [comment]
PING test works now, it runs until it succeeds or hits 20 times and then exits iPXE for the next boot option.

Testing on all Dellanox and Aruba went smoothly, a follow-up ticket (CASMNET-1099) for a needed Aruba config tweak to really seal the deal is next.

**Pull request merged**
